
TARGET_OS?=linux
TARGET_ARCH?=amd64

IMAGE_NAME=funman-ibex
IMAGE_TAG=$(TARGET_OS)-$(TARGET_ARCH)
BUILD_FLAGS?=

build-ibex-image:

build-ibex-images:
	make build-ibex-image TARGET_OS=linux TARGET_ARCH=amd64
